[package]
name = "parser"
version = "0.1.0"
authors = ["Yan Qian <qianyan@thoughtworks.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.5.5" #错误处理
